### ISSUE TITLE
Terninger(Ekstra kast)

### ISSUE THREAD

**Issue by ExpectedInt64** [VolkanIsik86/31_final#2]
- Vi skal have lavet en ekstra terning til spillet.

- Ved ens antal øjne på begge terninger, skal spiller kaste igen

- Hvis en spiller slår ens antal øjne 3 gange, går spiller til fængsel

**Comment by ExpectedInt64** [comment]
Terninger er tilføjet til Dev, mangler ekstra tur og fængsel

**Comment by Talha-Butt786** [comment]
Ekstra tur er tilføjet.
Mangler "Hvis en spiller slår ens antal øjne 3 gange, går spiller til fængsel".
